substitutions:
  name: "e-paper-weather-display"
  friendly_name: E-Paper Weather Display
  board: adafruit_magtag29_esp32s2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  # on_boot:
  #   - lambda: |-
  #       id(my_ota).set_auth_password("new pw here...");

esp32:
  board: ${board}
  framework:
    type: arduino

# Enable logging
logger:

# deep sleep most of the time
deep_sleep:
  run_duration: 60s
  # sleep_duration: 10min
  sleep_duration: 10s

# Enable Home Assistant API
api:
  encryption:
    key: !secret e-paper-weather-display-key

ota:
  - platform: esphome
    id: my_ota
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35
  miso_pin: GPIO37

font:
  - file: "gfonts://Roboto"
    id: small_font
    size: 18
    extras:
      - file: "gfonts://Material+Symbols+Outlined"
        glyphs: ["\ue1c6"] # sun-horizon

  - file: "gfonts://Roboto@700"
    id: big_font
    size: 48

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: homeassistant
    entity_id: sensor.my_weather_station_temperature
    name: "Temperature"
    id: weather_temp

text_sensor:
  - platform: homeassistant
    entity_id: weather.forecast_home
    attribute: temperature_unit
    name: "Temperature Units"
    id: weather_unit

display:
  - platform: waveshare_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdew029t5
    update_interval: 15s
    # update_interval: 15min
    rotation: 270
    reset_duration: 200ms
    # full_update_every: 2
    lambda: |-
      ESP_LOGI("display", "Updating display");
      it.print(0, 0, id(small_font), "Paradise Valley, Arizona (85253) \ue1c6");
      it.printf(0, 25, id(big_font), "%.1f %s",  id(weather_temp).state, id(weather_unit).state.c_str());
      // it.printf(64, 54, id(big_font), TextAlign::BASELINE_CENTER, buffer);

