esphome:
  name: album-art-workroom
  friendly_name: Album Art - Workroom 2
  name_add_mac_suffix: false

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Example configuration entry
web_server:
  port: 80
  version: 1