substitutions:
  name: home-assistant-voice-090d6c
  friendly_name: Home Assistant Voice 090d6c
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret home-assistant-voice-090d6c-key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
