substitutions:
  name: "presence-sensor-test"
  friendly_name: Presence Sensor Test
  board: seeed_xiao_esp32c3
  rxpin: GPIO20
  txpin: GPIO21

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  # on_boot:
  #   - lambda: |-
  #       id(my_ota).set_auth_password("set password here...");

esp32:
  board: ${board}
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret presence-sensor-test-key
    # key: "OJUmzDoc4fAl0hcu2Jf442dH54+pI6vJDI0L8GoIe0Y="

ota:
  - platform: esphome
    id: my_ota
    password: !secret ota_password

uart:
  id: uart_bus
  tx_pin: ${txpin}
  rx_pin: ${rxpin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret ap_wifi_pw

captive_portal:


# ld2450 configuration
ld2450:
  id: ld2450_radar
  throttle: 1000ms
  uart_id: uart_bus

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target