substitutions:
  name: ratgdov25i-eec2bc
  friendly_name: "Garage Controller - Bike "
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret ratgdov25i-eec2bc-key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
